---
title: "Tidy Coral"
author: "Bea"
date: "19/06/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, warning=FALSE, message=FALSE, }
library(tidyverse) #install.packages("tidyverse")
library(janitor) #install.packages("janitor")
library(skimr) #install.packages("skimr")
library(stringr)

## data filepaths/urls ----

## benthic data
benthic_url <- 'https://www.nodc.noaa.gov/archive/arc0054/0104255/1.1/data/0-data/cd08/100308OaAla03m.CSV'

## buoy data
buoy_url <- 'http://www.ndbc.noaa.gov/view_text_file.php?filename=mokh1h2010.txt.gz&dir=data/historical/stdmet/'
```

```{r benthic raw}
benthic_raw <- read_csv(benthic_url)
```

## Wrangle

```{r wrangle}
benthic <- benthic_raw %>% 
  janitor::clean_names() #beautiful names

names(benthic)

#Select our columns

benthic <- benthic %>%
  select(id_name, point, x, y, id_date) %>% 
  mutate(date = stringr::str_remove_all(id_date, "#"))

benthic

```
# Explore

```{r}
summary(benthic)
skimr::skim(benthic)

unique(benthic$date)
unique(benthic$id_name)

ggplot(benthic, aes(date, fill =id_name)) +
  geom_bar()
```
#Buoy data!

```{r}
buoy <- read_csv(buoy_url)

head(buoy)
```

The data is not in the right format because is an html that includes a text, not a csv. We can solve this by using 'read_table2()`. Before using that function we tried almost all the other functions to import data

```{r}
buoy_raw <- read_table2(buoy_url)

```

#Now wrangle both datasets

```{r tidy}
buoy <- buoy_raw

#Step1: overwrite column names

names(buoy) <- str_c( #joins two or more strings
  names(buoy),
  buoy %>% filter(`#YY` == "#yr"),
  sep = "_"
)
names(buoy)

## 2. clean up a bit more to get rid of the `#`s and the `/`s. 
names(buoy) <- str_replace_all(names(buoy), "#", "")  # replace `#` with nothing 
names(buoy) <- str_replace_all(names(buoy), "/", "_") # replace `/` with `_`

## inspect to make sure it worked
names(buoy)

## 3. remove redundant row with units
buoy <- buoy %>%
  filter(`YY_yr` != "#yr")
```
# Explore!

```{r}

ggplot(buoy, aes(WTMP_degC)) +
  geom_bar()

```

#Let's see the differences and try to fix them!
```{r}
head(benthic)
head(buoy)

#unite buoy dates

buoy <- buoy %>% 
  unite(date, c(YY_yr, MM_mo, DD_dy), sep = "-")

#join the datasets by date (left-join)

bb_join <- benthic %>% 
  left_join(buoy, by = "date") #this doesnt work well

bb_join %>% 
  select(id_name, x, y, date, hh_hr, mm_mn, WTMP_degC) %>% 
  head()

```

